### ISSUE TITLE
Allow for custom middleware to be passed to the module store

### ISSUE THREAD

**Issue by abettadapur** [Microsoft/react-redux-modules#1]
Right now, no extra middleware can be added to the store

**Comment by navneetg-msft** [comment]
Thanks for the feedback Alex.

This is by design, we believe that react-redux-modules is for large scale applications, and in our opinion redux-saga is best available middleware for large scale react+redux apps. It provides not just side effects but other cool features like channels.
Taking direct dependency on redux-saga makes our interface simple and we need not build another layer of abstraction.
We will keep our options open though and if we get more requests around this we will reconsider.

**Comment by codeocelot** [comment]
It's worth noting for future readers that #8 (Oct 4/2018) adds this functionality although it is not mentioned in the documentation. It looks like this: 

`<DynamicModuleLoader modules={ [{ middlewares: [middleware1, middleware2...] }] } >`
